version: "3.7"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - sqlserver-network
    container_name: sqlserver
    user: root
    ports:
      - "1433:1433"
    env_file: .env
    environment:
      SA_USERNAME: ${SA_USERNAME:-sa}
      SA_PASSWORD: ${SA_PASSWORD:-Dev1234!}
      ACCEPT_EULA: Y
    volumes:
      - ./volumes/data2:/var/opt/mssql/data
networks:
  sqlserver-network: