version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    env_file: .env
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq/:/var/lib/rabbitmq/
    networks:
      - rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-none}
      RABBIT_DEFAULT_VHOST: ${RABBIT_DEFAULT_VHOST:-my_vhost}
      RABBIT_DEFAULT_USER: ${RABBIT_DEFAULT_USER:-guest}
      RABBIT_DEFAULT_PASS: ${RABBIT_DEFAULT_PASS:-guest}

networks:
  rabbitmq:
    driver: bridge

volumes:
  rabbitmq:
